flit/__init__.py
flit/init.py
flit/license_templates/apache
flit/license_templates/gpl3
flit/license_templates/mit

This can be run with: `python3 -m flit.init` for now.
@Carreau - this is similar to your PR #9. I'm still going back and forth on whether I want it or not, but I spent some time working on it on the plane.
The main difference from your design is that I didn't want to tie it to git; instead I use entries from last time you ran the tool as defaults. I've also designed it so it would be fairly easy to build a different interface for the same functionality - I'm looking at Urwid as one possibility.

Add flit.init module

---

flit/install.py

This still complain for me, it seem to take a format string, like info, warning, message...etc.

fix debug format

---

flit/inifile.py

This gives an error message like `flit.inifile.ConfigError: Unrecognised metadata key: require (did you mean 'requires'?)`
Ping @Carreau

Suggest closest matching metadata key

---

flit/__init__.py
flit/common.py
flit/inifile.py
flit/install.py

This adds a `flit develop` subcommand which acts the same as `flit install --symlink` with the exception that it also installs any development requirements that are specified in the `flit.ini` file (under `develop-requires`).
I'll add tests and update relevant docs if you think this looks ok.

Add 'flit develop' command

---

flit/__init__.py
flit/install.py

The options to the `--deps` flag are 'all', 'install', 'develop', and 'none'. The default is 'all', which installs both the 'install' and 'develop' dependencies. If 'none' is specified, then no dependencies are installed.

Add flag to switch between sets of dependencies

---

flit/common.py

`docstring_lines[0],` was crashing, technically I am a little to harsh on the check but that's for teh good cause.

Die more gracefully on empty only-whitespace docstring.

---

flit/wheel.py

@Carreau :
```
[takluyver@tk2e15 flit]$ flit wheel
[takluyver@tk2e15 flit]$ md5sum dist/flit-0.7.2-py3-none-any.whl 
104fa2df7ba06b4c1369299761dc9866  dist/flit-0.7.2-py3-none-any.whl
[takluyver@tk2e15 flit]$ flit wheel
[takluyver@tk2e15 flit]$ md5sum dist/flit-0.7.2-py3-none-any.whl 
104fa2df7ba06b4c1369299761dc9866  dist/flit-0.7.2-py3-none-any.whl
```
There's two levels to this. If you run `flit wheel` twice on the same source tree locally, you should get the same results. But timestamps in the zip file reflect the time when you last pulled changes from git (git doesn't store mtimes), so someone else can't immediately reproduce the build from another clone. To make a properly reproducible build, set [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/). Try this …

Reproducible builds

---

flit/install.py

I was able to use flit on Windows after making this change.
https://docs.python.org/3/library/os.html#os.getuid

Fix windows incompatibility

---

flit/__init__.py
flit/wheel.py
tests/test_upload.py
tests/test_wheel.py

With this refactoring, WheelBuilder is no longer responsible for working out its own target file. A new wheel_main function gives it a temporary file to write to, and renames that afterwards (because we don't know the final name until we've processed the metadata).
Besides general loose-coupling principles, this should make it easier for `flit install` to work by building a wheel and calling pip with it: that machinery will use WheelBuilder directly to make the wheel in a temporary location.
I'm not sure whether WheelBuilder should get:
1. The path to a file it should open and write
2. A writable file object that it should write zip data to
3. A ZipFile object that it should write into.
Currently, this does 2, because it works neatly with mkstemp. Any clear advantages to the other …

Refactor WheelBuilder not to work out its own target file

---

flit/__init__.py
flit/_get_dirs.py
flit/install.py
flit/installfrom.py
tests/test_install.py

With this change, `flit install` (without `--symlink`) builds a wheel and invokes `pip` to install it. This should resolve issues @jhamrick saw previously where a package was installed to the wrong target directory. It should also result in `.exe` wrappers on Windows, rather than `.bat` wrappers.
`flit install` and `flit installfrom` also gain a `--python` parameter to run on another Python installation. E.g.:
```
flit install --python python2.7   # Legacy Python!
flit install --python /path/to/an/env/bin/python
source activate another_env
flit install --python python  # This targets the Python in the env
```
The default is still the Python which flit is running on. Flit doesn't need to be installed for the target Python (so it works on Python 2).

Install with pip

---

flit/wheel.py

`~=X.y` meaning `>=X.y` and `<(X+1)`.

Support "Compatible With" syntax for Legacy Python detection.

---

doc/history.rst
doc/index.rst
flit/inifile.py
flit/install.py

Ping @nonamedotc. I think this should make things easier for packagers - you would set `FLIT_NO_NETWORK=1`, and then there would be no need to copy classifiers around.
Any thoughts on the name or the way it works are welcome.

Add FLIT_NO_NETWORK environment variable

---

requirements-test.txt

Plugin is automatically enabled by PyTest.

Display warning by default during testing.

---

flit.ini
flit/wheel.py

metadata 2.0 specifies an extension for where to put this info, but it should work okay this way while flit is implementing 1.2.

include license file in wheels

---

flit/wheel.py

The 4th argument of `re.sub()` is maximum number of substitutions, not flags.
Found using [pydiatra](https://github.com/jwilk/pydiatra).

Fix misuse of flags in re.sub() calls

---

flit/__init__.py
flit/build.py
flit/sdist.py
flit/upload.py
flit/vcs/git.py
flit/vcs/hg.py
flit/wheel.py

These allow producing and uploading both wheels and sdists at the same time.

Subcommands 'flit build' and 'flit publish'

---

flit/common.py
flit/sdist.py
flit/wheel.py
tests/test_common.py
tests/test_sdist.py

This doesn't make sdists properly reproducible, but if you set `SOURCE_DATE_EPOCH` and build twice on the same machine (so the files have the same mtimes and permissions), you can get the same result.
CC @Carreau - we were talking about this somewhere else. I think this is all that's necessary to set the gzip timestamp:
```python
source_date_epoch = os.environ.get('SOURCE_DATE_EPOCH', '')
mtime = int(source_date_epoch) if source_date_epoch else None
gz = GzipFile(str(target), mode='wb', mtime=mtime)
tf = tarfile.TarFile(str(target), mode='w', fileobj=gz)
```

First steps towards reproducible sdist

---

flit/common.py
tests/samples/moduleunimportable.py
tests/samples/modulewithconstructedversion.py
tests/test_common.py

Per discussion in https://github.com/takluyver/flit/issues/141, this POC PR extracts a package under build's version & summary via `ast`, falling back to an import if that fails (because, for example, the `__version__` is anything but a simple string assignment).
This change allows packages to be built in an environment where the package being built can't necessarily be imported.

Extract a package's summary & version via ast

---

flit/__init__.py
flit/install.py
tests/test_install.py

`flit install -s` uses symlink, so this option can't work on windows.
this PR adds option using pth file to add project directory to `sys.path`.

add option to use pth file on install command

---

pyproject.toml

It looks like this may have been removed unintentionally when flit's own build config moved to `pyproject.toml` — it's definitely still required at runtime on Pythons < 3.6.

Bring back zipfile36 as a requirement for older Pythons

---

doc/pyproject_toml.rst
flit/init.py
flit/tomlify.py
tests/test_tomlify.py

In a folder containing `flit.ini`, run:
```shell
python3 -m flit.tomlify
```
I haven't currently given this a subcommand, because it's a rougher temporary tool.

Tool to convert flit.ini to pyproject.toml

---

README.rst

The steps under `Usage` section were numbered as: 1,2,2,4.
Updated that to 1,2,3,4.

Fix the numbering in Readme.

---

flit/buildapi.py
flit/common.py
flit/install.py
flit/wheel.py
tests/samples/altdistname.ini
tests/test_install.py
tests/test_wheel.py

The .dist-info folder should be like `pandoc_attributes-0.1.7.dist-info`, not `pandoc-attributes-0.1.7.dist-info`, so that it's unambiguous which bit is distribution name and which bit is version number.
I'm not sure the rules are clearly stated anywhere, but I've applied the same escaping PEP 427 specifies for wheel filenames.
Closes gh-149

Escape name components for .dist-info directory

---

doc/cmdline.rst
flit/build.py
flit/common.py
flit/inifile.py
flit/validate.py
tests/test_build.py
tests/test_common.py
tests/test_validate.py

This should make it easier to catch mistakes in packaging sooner.
The design is slightly awkward: a series of validation functions build up a list of problems. These are logged at 'error' level, and then a ConfigError is raised. I'm doing it this way so that it's easy to see multiple problems at once, not just the first one it finds.

More validation of packaging data

---

README.rst

Also rename `docs` to `documentation`

Remove mention of flit.ini as default file from readme.

---

flit/__init__.py
flit/upload.py
tests/test_command.py
tests/test_upload.py

These were deprecated in 0.13.
* *register* doesn't work with Warehouse, and since legacy PyPI no longer accepts uploads, it doesn't seem important to keep it. Users should now just upload packages directly.
* `flit build` now produces wheels and sdists, so the separate commands for them are no longer needed.

Remove subcommands: wheel, sdist, register

---

doc/history.rst
doc/pyproject_toml.rst
flit/common.py
flit/inifile.py
pyproject.toml
tests/samples/module1-pkg.toml

Add the ability to specify multiple URLs with names, like this:
```toml
[tool.flit.metadata.urls]
Documentation = "https://flit.readthedocs.io/en/latest/"
```
Closes #116.

Project URLs

---

.gitignore
.travis.yml
doc/history.rst
doc/pyproject_toml.rst
flit/common.py
flit/inifile.py
tests/samples/bad-description-ext.toml
tests/test_inifile.py

Fixes #166.
Until recently, PyPI only supported rst descriptions, falling back to plain text if the rst was invalid. Now a new metadata field `Description-Content-Type` lets us specify whether the description is rst, markdown or plain text. This new code uses that, picking the content type based on the file extension (`.rst`, `.md` or `.txt`). If the extension is something else, Flit will warn the user and leave the field unset, so it's up to PyPI what to do with it.
Markdown support has been a secret feature of Flit for some time, by using pandoc to convert markdown to rst (thanks @Carreau!). This makes it an official feature, and gets rid of the code to call pandoc, since PyPI can now handle markdown natively.

Official support for markdown and plain text descriptions

---

flit/install.py
tests/samples/requires-requests.toml
tests/test_install.py

In most cases, we can get the docstring and version number from the AST, so we don't need the package to be importable. If getting that info fails with ImportError, then we install the requirements before trying again.
Also, when we install directly (for --symlink or --pth-file), ensure that the requirements are installed to the target environment.
Closes gh-165
Closes gh-164

Only install reqs in sys.executable if needed

---

doc/cmdline.rst

Fix the list of projects that 'develop' installs

---

doc/pyproject_toml.rst

Consistent formatting of TOML lists with multiple elements for clarity.
I'm also confused by
>requires
>   A list of other packages from PyPI that this package needs. Each package may be followed by **a version specifier in parentheses**, like ``(>=4.1)``...
with the example of `... "requests (>=2.6)", ...` with the version in parentheses 
but then
>requires-extra
>   Lists of packages needed for every optional feature. The requirements
>   are specified in **the same format as for ``requires``.** 
with a more classic requirements.txt formatted example `... "pytest>=2.7.3", ...` without parens.

Tweak TOML lists in pyproject_toml.rst

---

flit/__init__.py

Don’t check for toml file in “installfrom”

---

pyproject.toml
requirements-test.txt

$ py.test --cov=flit
/home/.../site-packages/pytest_warnings/__init__.py:44:
UserWarning: pytest-warnings plugin was introduced in core pytest on 3.1, please uninstall pytest-warnings

Pytest-Warning now in core Pytest:

---

doc/pyproject_toml.rst

Fixes #208.
Minor change to make version constraint strings in the `requires-extra` docs uniform/consistent.

Uniform version constraint strings in docs

---

flit/common.py
tests/test_build.py

- Add module name to error about missing docstring.
- Add type annotation to function common.get_module_info signature
- Adapt tests to the new error message.

Fix #175 and add type annotation to arg. of `get_module_info`

---

flit/installfrom.py

Fixes #215 
Do not have any unit tests, but appears to work through my manual testing.
Errors will look something like this:
```
Traceback (most recent call last):
File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/installfrom.py", line 117, in install_local
deps='production').install()
File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/install.py", line 106, in __init__
self.ini_info = inifile.read_pkg_ini(ini_path)
File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/inifile.py", line 56, in read_pkg_ini
cp = _read_pkg_ini(path)
File "/Users/jacques/miniconda/lib/python3.6/site-packages/flit/inifile.py", line 156, in _read_pkg_ini
with path.open(encoding='utf-8') as f:
File "/Users/jacques/miniconda/lib/python3.6/pathlib.py", line 1181, in open …
```

try pyproject.toml then flit.ini

---

.travis.yml
README.rst

py.test is not recommended since pytest v3.0 (see https://github.com/pytest-dev/pytest/issues/1629)

py.test -> pytest

---

flit/buildapi.py
flit/common.py
flit/wheel.py
tests/test_common.py

Check for Python 2 support a little more thoroughly

---

tests/test_init.py

Previously, these were only passing because flit itself has a `pyproject.toml` and `LICENSE` file in project root.  If you assert on contents you would see for example email was actually `thomas@kluyver.me.uk` and not the expected `thomas@example.com`.

Fix bogus flit init tests

---

flit/vcs/hg.py

find_repo_root's parent-directory-walking behaviour doesn't behave quite as expected when called with a relative path; if called in any directory except the root of the repo it would return None, which calling code did not expect.

Bugfix for building sdists in Mercurial repos

---

flit/common.py

This e.g. allows using [future-fstrings](https://github.com/asottile/future-fstrings), which I’d like to use in flying-sheep/get_version#3
You can check that this works via:
```py
#!/usr/bin/env python3.5
import ast
st = ast.parse(b"# coding: future-fstrings\nprint(f'hi {ast}')")
exec(compile(st, filename="", mode="exec"))
```

Allow specifying encodings

---

flit/inifile.py
tests/samples/missing-description-file.toml
tests/test_inifile.py

Show a nice error if the configured description-file is missing

---

.gitignore
tox.ini

Per discussion in https://github.com/takluyver/flit/issues/231, this PR introduces config for tox that allows running flit's unit test suite against multiple Python interpreters outside of the context of GitHub's CI.

Add tox config

---

doc/history.rst

[PEP 263](https://www.python.org/dev/peps/pep-0263/) support isn’t just about hacks, even though I think that using no normal encoding but utf-8 is wise.

Phrase encoding support more neutrally

---

pyproject.toml

I had to add these to make the docs build work.
These instructions don't give a dev env where the docs can be generated locally:
https://github.com/takluyver/flit#development
I found this option:
```
flit install --deps all
```
Maybe recomment that to hack on `flit`?

Add missing doc dependencies in pyproject.toml

---

tests/test_inifile.py

Error seem to be due to pytest wrapping errors, and the str()
representation of the error not always having the full error message of
the underlying error.

Fix CI error on test_misspelled_key

---

flit/__init__.py
flit/install.py
tests/test_find_python_executable.py
tests/test_install.py

Fixes #285 
I also fixed a deprecation warning for an invalid escape sequence.

fix shebang in scripts installed with --symlink 

---

.travis.yml
tox.ini

Released yesterday: https://discuss.python.org/t/python-3-8-0-is-now-available/2478
We can also simplify the CI matrix a bit because Xenial is now default.

Add support for Python 3.8

---

flit/common.py
flit/inifile.py
flit/init.py
tests/test_init.py

The core metadata spec says it should be optional  https://packaging.python.org/specifications/core-metadata/#author-email
Related: https://github.com/takluyver/flit/issues/236
Anecdotally, I've seen people confused about what to do when they don't want a public email associated (currently they can only use flit by entering a fake email address there)

make Author-email field optional

---

flit/__init__.py

[bpo-38905](https://bugs.python.org/issue38905)
On Python 3.7.2 or later, `sys.executable` returns the wrong executable inside venv on Windows unless you invoke the interpreter with an absolute path. It seems that the behaviour is expected and unlikely to be fixed (at least not any time soon). Core devs seem to approve the `shutil.which()` workaround.

Make Python command absolute before calling subprocess

---

README.rst
bootstrap_dev.py
doc/development.rst
doc/index.rst
flit/__init__.py
flit/install.py
flit_core/flit_core/build_thyself.py
tests/test_install.py
tox.ini

Fixes #291, cc @uranusjr 
This adds a `bootstrap_dev.py` script to make it easy to get a development install of Flit to experiment with.

Development install for Flit itself

---

flit_core/flit_core/inifile.py

I have added the missing underscore character in the regular expressing for Python 2 `isidentifier()` check.

Allow underscore for Python 2 identifiers

---

bootstrap_dev.py

Since Flit itself support down to 3.5, the bootstrap script probably needs to as well. Unfortunately pathlib support was spotty back then.

Make bootstrap_dev work on Python 3.5

---

flit/sdist.py
flit_core/flit_core/common.py
tests/samples/packageinsrc/pyproject.toml
tests/samples/packageinsrc/src/module1.py
tests/test_sdist.py

This adds something like
```python
package_dir = \
{'': 'src'}
setup(...
package_dir=package_dir,
)
```
to setup.py if the module is found inside a `src/` prefix.
Fix #302.
Syntax reference: https://docs.python.org/3.9/distutils/setupscript.html#listing-whole-packages

Correctly set up package_dir for src/ prefix

---

flit/install.py

The batch `echo` mode is ON by default on Windows. As a result, running
a custom CLI keep printing out the script location and the command that
was run.
Here is a custom CLI tool called `git-conventional-commit`,
With echo OFF (expected behavior):
```bash
git-conventional-changelog . -o
-o requires argument
Usage:
git-conventional-changelog REPO [--output=<str>][--show-scope][--fake][--verbose]
git-conventional-changelog -h | --help
git-conventional-changelog --version
```
With echo ON (noise added to the command output):
```bash
git-conventional-changelog . -o
"C:\Users\Stephen\venv_projects\mylibs\git_history\venv\Scripts\python.exe" "C:\Users\Stephen\venv_projects\mylibs\git_history\venv\Scripts\\git-conventional-changelog" . -o
-o requires argument
Usage:
git-conventional-changelog …
```

fix(windows): Use `@echo off` in batch scripts

---

doc/cmdline.rst
flit/__init__.py
flit/build.py
flit/sdist.py
flit/upload.py
flit_core/flit_core/sdist.py
tests/test_sdist.py

The setup.py is a compatibility measure until we can rely on PEP 517. This lets people who want to bring the future forwards start relying on PEP 517 now.
Closes gh-304

Add an option to make sdists without setup.py

---

doc/development.rst

To get flit installed for development, pygments is also required but missing in the documentation.

docs: add pygments to prerequisites for dev

---

doc/pyproject_toml.rst

Update example pyproject.toml, fix requires-python (fixes #326)

---

flit/vcs/git.py

With this change, the git submodules:
* Get included recursively instead of an empty directory
* Is correctly excluded from source distribution when `exclude` option is used for sdist
I would love to implement tests for this, however I cannot find the appropriate placement for it.

Handle git submodules inclusion in sdist (fix #323)

---

flit/validate.py
tests/test_validate.py

I ran into a problem when installing another project with flit for development purpose using `flit install --pth-file`.  The user had a non-existing home directory set (`/nonexistent') and therefore the download of the trove classifiers failed.
The `/nonexistent` "home" directory is used on POSIX systems to denote a user without a home directory, e.g. user `nobody` or users only set up for services.
These proposed changes ensures that a valid directory is returned by the `flit.validate.get_cache_dir()` function. 
If the `flit`-subdirectory of the cache-directory does not exist and could not be created, a temporary directory is used instead. To ensure that always the same temporary directory is used, the function is wrapped with the `functors.lru_cache()`.
A tests for this new behavior is …

ensures cache dir does exist

---

README.rst
doc/history.rst
doc/pyproject_toml.rst
flit/init.py
pyproject.toml

All projects with metadata in pyproject.toml (not flit.ini) should continue to work with flit_core 3.x. I'm also planning to drop support for Python 2 again, but that will be handled automatically with the Requires-Python metadata field.

Declare projects compliant with flit_core 3.x by default

---

flit/__init__.py
tests/test_find_python_executable.py

Fixes #330 
I also took the liberty of adding type hints.
Behaviour before:
```bash
$ flit install --python pyhton
Python executable None not found
$ flit install --python ls
ls: cannot access 'import sys; print(sys.executable)': No such file or directory
Traceback (most recent call last):
File "/PATH/bin/flit", line 8, in <module>
sys.exit(main())
File "/PATH/lib/python3.7/site-packages/flit/__init__.py", line 168, in main
python = find_python_executable(args.python)
File "/PATH/lib/python3.7/site-packages/flit/__init__.py", line 33, in find_python_executable
universal_newlines=True,
File "/PATH/lib/python3.7/subprocess.py", line 411, in check_output
**kwargs).stdout
File "/PATH/lib/python3.7/subprocess.py", line 512, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: …
```

Fix find_python_executable error

---

flit/init.py
tests/test_init.py

When doing `flit init`, flit will look for a readme file in the root of the project. (`readme.md`, `readme.rst`, `readme.txt`, lower or uppercase). If found it will ask the user to include it in the `pyproject.toml` file as an `description-file` entry.

When doing `flit init`, if readme file is available, add it to pyproject.toml

---

flit/install.py
tests/test_install.py

Initial PEP 610 support is merged in pip master (will be in pip 20.1). This PR is meant to add PEP 610 support to flit.
Currently `flit install` (without --symlink/--pth-file) builds a wheel then invokes `pip install {temporary wheel file}`. This means pip will consider the wheel is being installed from a direct url which is actually a temporary file and will record that temporary url. The desired behaviour is to record the url of the local project directory.
To achieve that desired behaviour, there are two options:
1. Change `install_with_pip()` to merely do `pip install {self.directory}` and let pip do the PEP 517 build and install. That is the simplest approach, but has the drawback of possibly invoking another version of `flit` as build backend, and being somewhat slower. 
2. Keep …

PEP 610 (direct_url.json) support

---

.travis.yml
appveyor.yml
flit/config.py
flit/install.py
flit/sdist.py
flit/wheel.py
flit_core/flit_core/build_thyself.py
flit_core/flit_core/buildapi.py
flit_core/flit_core/common.py
flit_core/flit_core/config.py
flit_core/flit_core/sdist.py
flit_core/flit_core/tests/test_common.py
flit_core/flit_core/tests/test_config.py
flit_core/flit_core/tests/test_sdist.py
flit_core/flit_core/wheel.py
tox.ini

For Flit 3, we're going back to requiring Python 3. It will still be possible to install projects from source on Python 2, because pip will find a 2.x version of `flit_core` to use.
There's still some messiness with using pathlib before Python 3.6, when lots of APIs started to accept Path objects.

Re-drop Python 2 support in flit_core

---

flit/vcs/git.py
tests/test_build.py
tests/test_sdist.py

Fix to handle unicode filenames

---

flit_core/flit_core/common.py

Because a likely reaction to this useful warning is to copy paste this into the module and adjust x, y, and z but then it's convenient to not have to add spaces in addition.

add spaces to warning about missing __version__

---

flit/install.py
flit_core/flit_core/common.py

I have some console scripts which are class methods (the main remains the same, but I have a hierarchy of subclasses in different packages which fill out functionality for several different entry points)
```
[tool.flit.scripts]
foo="bar.baz:Spam.main"
```
This caused flit to fail when doing editable installs (symlink/pth-file), but work when doing "regular" installs (via pip)
I found that the template used here expected _only_ a single part function call.
This PR takes the [template as used by pip (provided by the vendored distlib)](https://github.com/pypa/pip/blob/master/src/pip/_vendor/distlib/scripts.py#L41) and modifies the functions that interact with the template to provide the imported name separate from the function name.

Update generated scripts to match pip installed scripts

---

flit_core/flit_core/wheel.py
tests/test_wheel.py

Fixes #362
This commit writes the metadata files with the permission bits set to “readable by all” to fix that.

Write metadata readable

---

flit/install.py

Hi,
While working on a Debian package that uses flit, I noticed that the package could not be built reproducibly (https://reproducible-builds.org).
This patch will aid to reproducibly build Debian packages of projects that use flit.

Deterministically produce RECORD file

---

flit_core/flit_core/common.py
flit_core/flit_core/wheel.py
tests/samples/modulewithlocalversion/modulewithlocalversion.py
tests/samples/modulewithlocalversion/pyproject.toml
tests/test_wheel.py

According to new rules in https://packaging.python.org/specifications/binary-distribution-format/#escaping-and-unicode
Specifically the ones introduced in https://github.com/pypa/packaging.python.org/pull/844
Supersedes #388
Fixes #383, fixes #383, fixes #394

New normalization for dist-info and wheel names

---

flit_core/flit_core/common.py
flit_core/flit_core/tests/test_common.py

Closes #387
Also, update which fields are required in metadata files (closes #102).

Indent multiline values in metadata to make valid METADATA file

---

doc/pyproject_toml.rst
flit/validate.py
tests/test_validate.py

Listing "Private :: Do Not Upload" in the classifiers list is a way to protect a package from accidental uploading on PyPI. This is a special case because it is not listed in the trove classifier.
References:
+ Origin: https://twitter.com/di_codes/status/1097220464445931525
+ It is implemented on PyPI side: https://github.com/pypa/warehouse/pull/5440
+ It's not documented yet: https://github.com/pypa/packaging.python.org/issues/643
+ It is supported by twine: https://github.com/pypa/twine/issues/557
P.S. Sorry for PR without making an issue upfront. I think this is the case that isn't hard to implement, so it's better to show than explain :)

Allow `Private :: Do Not Upload` classifier.

---

tox.ini

Tests failed on PR #416 for Python 3.4, because it got a version of `attrs` that was too new.
In fact the offending release has been yanked (see https://github.com/python-attrs/attrs/pull/807 )... but it seems that the version of pip which supports Python 3.4 is too old to know about yanking, so it needs this workaround.

Pin attrs <21 for testing on Python 3.4

---

flit/upload.py

Hi friend!
This is needed by GitLab to support uploads from flit (GitLab works fine with twine).
Addresses #364 of takluyver/flit
Addresses [#333964 of gitlab.com/gitlab-org/gitlab](https://gitlab.com/gitlab-org/gitlab/-/issues/333964)
The most useful one-line of code I ever wrote I believe. If this is merged, we will be able to use gitlab as a fully functional pip repository that works with flit. 
Cheers!
Matcha

Support SHA256 hashes

---

flit_core/flit_core/sdist.py

I was not able to tell if there is a downside to using the same
metadata as the wheel but a cursory investigation revealed
that it's what Poetry does.  setuptools omits the requirements
but its PKG-INFO appears to be otherwise identical to the wheel's
METADATA file.  flit appears to be a bit of an outlier in creating
a barebones PKG-INFO file.
Closes #409.

Reuse wheel metadata in sdist

---

flit_core/flit_core/config.py
flit_core/flit_core/tests/samples/pep621_nodynamic/pyproject.toml
flit_core/flit_core/tests/test_config.py

The code loading the config file was doing the wrong thing when `dependencies` were specified but not `optional-dependencies`.
Closes #432.

Fix installing dependencies specified in [project] table

---

flit/wheel.py
flit_core/flit_core/buildapi.py
flit_core/flit_core/tests/test_buildapi.py
flit_core/flit_core/wheel.py
tests/test_wheel.py

This is a very rough proof of concept for `build_wheel_for_editable`, as described in https://discuss.python.org/t/standardising-editable-mode-installs-runtime-layout-not-hooks/4098/55 and prototyped in https://github.com/pypa/pip/pull/8212. 
It works by adding a `.pth` file in the transient wheel, and should therefore behave identically as `flit install --pth-file`.

PEP 660 support

---

doc/cmdline.rst
doc/history.rst
doc/upload.rst
flit/__init__.py
flit/upload.py
tests/test_upload.py

This PR adds support for handling a custom path for the `.pypirc` file. Previously the file was assumed to always be in `~/.pypirc`, which can be an issue depending on the build environment that is being used as stated in #426.
The path can be passed through the `--pypirc` argument, as such:
```sh
flit publish --pypirc .pypirc
```
A unit test was added to ensure the parsing is correctly done when the custom path is specified.

Add custom pypirc support

---

README.rst
doc/pyproject_toml.rst

This PR updates README.rst to reflect the new project metadata format generated with `flit init`.
A few other rephrasing and minor whitespace and quote modifications here too.

Update README.rst for flit_core >=3.2 metadata

---

doc/requirements.txt

Require newer Sphinx for building docs on RTD

---

flit/__init__.py

Autogenerating `setup.py` was a workaround to let pip install from source before PEP 517. pip supports PEP 517 since 19.0 (January 2019). Of course it supports installing wheels since much earlier (2013), and this is the default installation method. So I'm gradually moving towards getting rid of the generated `setup.py` file.
In Flit 3.4 (2021-10-10), I added a message saying that the default would change, and adding a (no-op) `--setup-py` option.  This PR will make `--no-setup-py` the default behaviour, and update the message accordingly.
I haven't decided when to merge this yet. The `flit` command line tool is meant as a developer tool, so I think it's reasonable to do changes like this relatively quickly (unlike in the lower-level `flit_core` package). But the purpose of adding the …

Don't generate setup.py by default.

---

flit/install.py
flit_core/flit_core/common.py
tests/test_install.py

A symlink install with a `src` layout would go wrong because it tried to create a `src` directory in site-packages, and a `.pth` file would separately go wrong because it didn't make the path absolute before writing it. Both problems were introduced by #468.
Closes #471

Fix development installs

---

doc/cmdline.rst
doc/conf.py
doc/development.rst
doc/flit_ini.rst
doc/pyproject_toml.rst
flit/__init__.py
flit_core/flit_core/build_thyself.py
flit_core/flit_core/tests/samples/module2.py
flit_core/flit_core/tests/test_wheel.py
pyproject.toml
tests/test_validate.py

While GitHub does redirect, it is good practice to fix links.
And the redirect will last only until Thomas decide to fork it again.
-- 
Note that my autoformater was a bit overzealous in replacing some simple to double quotes, I can redo those files if you wish to.

Replace /takluyver/ by /pypa/ where relevant

---

flit/__init__.py

The default changed in 3.5 (2021-11-18). These messages were meant to be temporary, to alert people who might want a `setup.py` in their sdists that they should explicitly request it. I don't want to keep drawing attention to the feature, because eventually the `--setup-py` option will go away.

Remove messages about setup.py default changing

---

flit/__init__.py

Help for --setup-py: don't say it's the default

---

flit_core/flit_core/common.py
tests/samples/altdistname/pyproject.toml

In line with this correction in the wheel spec: https://github.com/pypa/packaging.python.org/pull/1032
The [spec for `.dist-info` directories](https://packaging.python.org/en/latest/specifications/recording-installed-packages/) already requires this, by referring to [PEP 503](https://www.python.org/dev/peps/pep-0503/#normalized-names).

Lowercase distribution name in wheel filename and .dist-info folder name

---

doc/pyproject_toml.rst
flit/install.py
flit_core/flit_core/common.py
flit_core/flit_core/config.py
flit_core/flit_core/sdist.py
flit_core/flit_core/tests/samples/with_data_dir/LICENSE
flit_core/flit_core/tests/samples/with_data_dir/README.rst
flit_core/flit_core/tests/samples/with_data_dir/data/share/man/man1/foo.1
flit_core/flit_core/tests/samples/with_data_dir/module1.py
flit_core/flit_core/tests/samples/with_data_dir/pyproject.toml
flit_core/flit_core/tests/test_sdist.py
flit_core/flit_core/tests/test_wheel.py
flit_core/flit_core/wheel.py
tests/test_install.py

Corresponding to setuptools' `data_files`, but less flexible: you just get one directory, which will be mapped to wherever the installer decides to put the 'data' component of the wheel (typically the prefix path).
Closes #358.

External data directory

---

flit_core/flit_core/common.py

The API we were using before was deprecated and has started issuing warnings. I've based the new code on this example in the importlib docs: https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly
Closes #496.

Use newer importlib APIs when loading module for docstring & __version__

---

doc/bootstrap.rst
flit_core/bootstrap.py
flit_core/bootstrap_install.py
flit_core/flit_core/tests/test_wheel.py
flit_core/flit_core/wheel.py
flit_core/pyproject.toml

Improved version of #481 based on comments [here](https://github.com/pypa/build/issues/430#issuecomment-1008874876).
Details from help:
```
$ python -m flit_core.wheel --help
usage: wheel.py [-h] [--srcdir SRCDIR] [--outdir OUTDIR]
options:
-h, --help            show this help message and exit
--srcdir SRCDIR, -s SRCDIR
source directory (defaults to current directory)
--outdir OUTDIR, -o OUTDIR
output directory (defaults to /Users/jameshilliard/flit/flit_core/dist)
```
```
$ python bootstrap.py --help
usage: bootstrap.py [-h] {build,install} ...
positional arguments:
{build,install}
options:
-h, --help       show this help message and exit
```
```
$ python bootstrap.py build --help
usage: bootstrap.py build [-h] [--outdir OUTDIR]
options:
-h, --help            show this help message and …
```

Add bootstrap script/wheel module for flit_core

---

doc/cmdline.rst

The link in the docs is outdated.

Update link to external pip environment variables docs

---

flit_core/flit_core/config.py
pyproject.toml

This allows unvendoring tomli assuming Python 3.11 or newer. FIxes https://github.com/pypa/flit/issues/544

Use tomllib instead of vendored tomli when available

---

flit/upload.py
tests/test_upload.py

Continue with a warning rather than error-ing out.
Fixes #538 (the part of it that Flit can control, at least)

Catch errors getting/setting password with keyring

---

doc/pyproject_toml.rst
flit_core/flit_core/config.py
flit_core/flit_core/tests/samples/normalization/pyproject.toml
flit_core/flit_core/tests/test_config.py

The package name is used as the default module name. Technically, the
module name must be normalized (no hyphens), so for convenience set the
default module name to the normalized package name, with hyphens replaced
by underscores.
---
Normalization is mentioned in [PEP426](https://peps.python.org/pep-0426/#name) and came up before in #149. ~The change proposed here was not tested (it is proposed to gauge interest and sentiment). Additionally, the documentation is not touched, but I feel normalization may be left implicit since~ a package name with hyphens isn't a valid import name to begin with.
_edit:_ To clarify, with this change the default module name for the `aiohttp-remotes` project becomes `aiohttp_remotes`.

Normalize module name default value

---

flit_core/flit_core/common.py
flit_core/flit_core/tests/test_common.py

Closes #476 and #591
Add support for compatible release version specifier '~=' and version matching clause '=='.
I was happy to see that someone picked up this issue in #586 , but it seems like the conversation stalled a bit, so here I am. It's something that was bothering me for a while now and it would be nice to see it fixed 😄

Modify regex for checking py2 compatibility

---

doc/pyproject_toml.rst
pyproject.toml

Since otherwise the documentation may not work for the current stable release, if new changes/features haven't yet been released.
In addition, the links now consistently use the `flit.pypa.io` custom domain, rather than the Read the Docs domain.
Closes #588.

Link to the stable release docs in project metadata

---

flit_core/flit_core/common.py
flit_core/flit_core/tests/samples/moduleunimportabledouble.py
flit_core/flit_core/tests/test_common.py

Some projects seem to use multiple assignments which currently only seems to work if `__version__` is the first variable being assigned to.

Fix ast version parser for multiple assignments

---

flit_core/LICENSE
flit_core/pyproject.toml
pyproject.toml

As far as I understand (IANAL), distributing the package on PyPI without the license text violates your own license terms.

Include license file in the built package

---

.github/workflows/test.yml
flit_core/flit_core/config.py
tests/test_tomlify.py
tox.ini

dba0f317c52d3c9fa29792a0beb0c0abf4476a23 removed some, but not all of the imports of the vendored tomli. This PR adds the same tomllib > tomli fallback to the tests and adjusts the tox.ini test deps accordingly.
Additionally, this adjusts flit-core to only use its vendored tomli when tomli isn't already installed. In Fedora, we bootstrap tomli differently, so we `rm -r` the vendored version. This change makes it so Fedora and other distributions don't also have to patch flit_core.config.
/cc @hroncok

Remove vestigial tomli usage 

---

.github/workflows/test.yml

`ubuntu-latest` now refers to 22.04, which doesn't have 3.6 available.

Use Ubuntu 20.04 to test on Python 3.6

---

flit_core/README.rst
flit_core/pyproject.toml

Provide additional context for flit-core, fixes https://github.com/pypa/flit/issues/612.

Flit core readme

---

tox.ini

`whitelist_externals` was removed and deprecated in tox v 4.0.0.rc4 We should use `allowlist_externals` instead.
https://tox.wiki/en/latest/changelog.html#deprecations-and-removals-4-0-0rc4

tox: use allowlist_externals option instead of whitelist_externals

---

doc/pyproject_toml.rst
flit/__init__.py
flit/build.py
flit/sdist.py
flit/upload.py

From the discussion on #522, this adds an option to not use the VCS to get the list of files to include in the sdist. So `flit build --no-use-vcs` is equivalent to `python -m build` with flit_core as a backend. The idea is that in a future version (4.0?), this will become the default, and you will need to use `--use-vcs` to explicitly choose the sdist-files-from-vcs behaviour.
I've also tried to improve the documentation about what gets included in the sdist by default.

Add --use-vcs and --no-use-vcs flags for build commands

---

flit_core/flit_core/common.py
flit_core/flit_core/tests/samples/imported_version/package1/__init__.py
flit_core/flit_core/tests/samples/imported_version/package1/_version.py

In cases where packages import `__version__` from version modules (like
those generated by setuptools_scm or attribution), this allows flit-core
to use the existing ast-based logic to read the version directly from
those files when possible. It checks a few well-known version filenames,
including the package-level `__init__.py` as usual, with `__init__.py`
taking precedence over external version files if an assigned
`__version__` value exists in multiple places.
This makes flit more resilient to reading version from these packages,
even if their `__init__.py` has transitive imports that aren't available
in the environment at build time (eg, conda-forge builds). It also
reduces the number of times when flit has to fall back to actually
importing the `__init__.py` file rather than reading …

Read version from version files via ast

---

flit_core/flit_core/sdist.py

This allows Flit to create byte-for-byte identical sdists even without `SOURCE_DATE_EPOCH` set, if run on the same checkout of the source files on the same machine.
Where timestamps relate to a file we're packing from the filesystem, we use that file's mtime, unless SOURCE_DATE_EPOCH overrides it. But other timestamps, including this one in the gzip format, automatically use the current time and thus aren't reproducible. We already set a fixed default timestamp for generated files added to wheels, for the same reason:
https://github.com/pypa/flit/blob/532bdaabafe0660b6c7494d8043ec4fa15b286a8/flit_core/flit_core/wheel.py#L145-L149
This doesn't matter for 'proper' reproducible builds, since to do that you'd set SOURCE_DATE_EPOCH anyway. But being readily able to generate identical …

Use fixed default for gzip timestamp in sdists

---

flit_core/flit_core/sdist.py
flit_core/flit_core/tests/test_sdist.py

Normalize generated source distribution names using the same rules as wheels, as required by PEP 625 [1].  This aligns flit_core with other modern PEP 517 backends such as hatchling.
[1] https://peps.python.org/pep-0625/
Fixes #626

flit_core: Normalize sdist names according to PEP 625

---

flit/upload.py

The current error occurs due to ConfigParser performing environment variable substitution, causing issues when the password contains the '%' symbol. To fix this, I replaced ConfigParser with RawConfigParser, which avoids environment variable substitution.
```
Found 8 files tracked in git                                        I-flit.sdist
Built sdist: dist/resu-0.1.2.tar.gz                            I-flit_core.sdist
Copying package file(s) from /var/folders/zv/q47bvs0s6rgd8mxck25__yh40000gn/T/tmpjl6_47_1/resu-0.1.2/resu  I-flit_core.wheel
Writing metadata files                                         I-flit_core.wheel
Writing the record of files                                    I-flit_core.wheel
Built wheel: dist/resu-0.1.2-py2.py3-none-any.whl              I-flit_core.wheel
Traceback …
```

Avoid Environment Variable Substitution by Using RawConfigParser

---

pyproject.toml
tox.ini

Python 3.7 is already end of life (security updates ended earlier this year), so we can bump the minimum version up.
As usual, I'm being more conservative with the compatibility of `flit_core`, so you can still build packages on older versions of Python.
Prompted by #658.

Require Python >=3.8 for flit CLI

---

flit/install.py

We recently switched to flit and I came across this issue when I installed a package using the "symlink" mode. What I did was adding more data files and then re installing the package to create the symlinks to the recently added data files:
```console
flit install -s
Traceback (most recent call last):
FileExistsError: [Errno 17] File exists: '/home/wilfred/workspace/deployment/assets/share/freva/deployment/config/create_tables.sql' -> '/tmp/py_311/share/freva/deployment/config/create_tables.sql'
```
Since without `-s` any existing data files would be overridden anyways I figured it's ok to delete any existing data files.

Remove destination data files if they exist.

---

flit/upload.py
tests/test_upload.py

The username for keyring should look like `pypi_token:project:<project_name>` (using the [normalised](https://packaging.python.org/en/latest/specifications/name-normalization/) name), or `pypi_token:user:<username>`. If neither are found, it falls back to looking for a password (but if you have 2FA enabled on PyPI, uploads *have* to use tokens now).
I'd like to make some more tooling for conveniently creating tokens, but there isn't a PyPI API for it yet.
While I'm looking at this code, I've also simplified things a bit so that `FLIT_USERNAME` and `FLIT_PASSWORD` environment variables override details in `.pypirc` even if you use `--repository`, and it figures out the repository details before building the packages.

Look for PyPI tokens in keyring when uploading

---

pyproject.toml

According to docs https://flit.pypa.io/en/stable/cmdline.html#flit-install:
> Flit calls pip to do the installation.
but pip was not specified as runtime dependency of flit.
Fixes: https://github.com/pypa/flit/issues/646

deps: Add missing runtime dependency on pip

---

doc/requirements.txt

The docs build on #667 failed, complaining that some extension requires a newer version of Sphinx.

Update Sphinx & sphinx-rtd-theme for RTD

---

flit/__init__.py
tests/test_find_python_executable.py

pip --python option can take both the path to a Python executable or the path to a virtual environment, greatly improving the user experience.
Teach flit to do the same.

flit: improve the --python option

---

flit/upload.py
flit_core/flit_core/common.py
flit_core/flit_core/tests/test_common.py

[PEP 643](https://peps.python.org/pep-0643/) introduces Metadata 2.2, where fields can either be static (default) or marked as dynamic. 
[PEP 685](https://peps.python.org/pep-0685/) introduces Metadata 2.3, that specifies how to normalize extra names.
This PR bumps the Metadata version to 2.3. `flit` has always written and published static metadata in both wheel `METADATA` and sdist `PKG-INFO` and therefore this PR does not intend to add new support for recording dynamic metadata into distributions. This should not be confused with the `dynamic` metadata in the pyproject.toml files, which are dynamic in flit and remain supported (PEP 621).
Upgrading to the newer Core Metadata standards has advantages for the python packaging ecosystem. It makes it possible for resolvers to read metadata …

Implement Metadata 2.3

---

flit_core/flit_core/wheel.py

https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp
The alternative proposed should work in all Python versions flit supports

datetime.utcfromtimestamp is deprecated in Python 3.12, avoid using it

---

flit_core/flit_core/common.py

The ast.Str class was deprecated in 3.8 and will be removed in 3.14

MNT: fix compatibility with Python 3.14

---

flit/buildapi.py

I'm not 100% sold on this: the removal would break things that might otherwise work, and it's a tiny bit of complexity by itself. But any project still specifying `flit.buildapi` is probably also using old-style metadata (`[tool.flit.metadata]` table), which 4.0 will likely not support (#673), and that is enough complexity to be worth cleaning up.
- `flit.buildapi` added in 0.12 (November 2017)
- `flit_core.builadpi` added in 2.0 (November 2019)
- New-style metadata (`[project]` from PEP 621) added in 3.2 (March 2021)
Using `python -m build`, this warning is visible. Using `pip wheel` (and presumably any other pip command that does a build), it isn't (`pip wheel -v` shows it). I don't think there's anything we can do to make it more visible, but a warning that only some people see is …

Warn if packages still using flit.buildapi instead of flit_core.buildapi

---

flit_core/flit_core/vendor/README

Provides extra context for readers.

Add a hyperlink to the bootstrapping problem.

---

flit/upload.py

It was a temporary url, still redirect for some GET but should not be used.

Pypi.io does not exists anymore.

---

.github/workflows/test.yml
flit_core/flit_core/config.py
tests/test_find_python_executable.py

Some changes to `os.path.isabs()` (https://github.com/python/cpython/issues/44626 ) caused test failures.

Fix tests on Python 3.13 & Windows

---

.github/workflows/test.yml

Codecov is adding an extra ~20 seconds to each CI job, because it hits a rate limit and retries several times before timing out. I think giving it the token should work around this.

Provide token to upload coverage data to codecov

---

.github/workflows/test.yml

The `ubuntu-latest` platform on Github actions is now 24.04, and doesn't have Python 3.7 available any more.

Move Python 3.7 tests to Ubuntu 22.04

---

tox.ini

Substitution with `{posargs}` allows devs to pass additional arguments to the tox command. Especially helpful if you like to run only a subset of tests for debugging. E.g
```
tox -e py313 -- --no-cov flit_core/tests_core/test_config.py
py313: commands[0]> python -m pytest --cov=flit --cov=flit_core/flit_core --no-cov flit_core/tests_core/test_config.py
```
https://tox.wiki/en/latest/config.html#substitutions-for-positional-arguments-in-commands

Add tox posargs

---

flit_core/flit_core/common.py
flit_core/flit_core/config.py
flit_core/tests_core/test_common.py
flit_core/tests_core/test_config.py
pyproject.toml

Enable the new License-Expression and License-Files fields.

Package metadata version 2.4

---

.bumpversion.cfg
doc/conf.py
doc/history.rst
doc/pyproject_toml.rst
flit/__init__.py
flit_core/flit_core/__init__.py
pyproject.toml

Prepare to release 3.11

---

flit_core/flit_core/common.py
flit_core/tests_core/samples/annotated_version/module1.py
flit_core/tests_core/samples/annotated_version/pyproject.toml
flit_core/tests_core/test_common.py

I recently tried to update a package to use a ``Final`` annotation for the ``__version__`` attribute, but realised that Flit doesn't support annotated assignment. This PR adds support and tests.
A

Support annotated assignment for ```__version__``` strings

---

flit_core/flit_core/config.py
flit_core/tests_core/test_config.py

Add additional check for project.license.file

---

flit/install.py
flit_core/flit_core/config.py
tests/test_sdist.py
tests/test_tomlify.py
tests/test_upload.py

Extracted out of #731, I noticed a few now-unused imports.
A

Remove unused imports

---

flit_core/flit_core/config.py
flit_core/tests_core/test_common.py
flit_core/tests_core/test_config.py

Closes #723.
cc @takluyver @cdce8p 
A

Support compound SPDX licence expressions

---

flit/build.py

I'm doing this mainly to get rid of the deprecation warning saying that the default filter will change in 3.14. I don't think sdists should be using any of the fancier features in the tar format. If someone comes up with a valid use case why an sdist might need e.g. a symlink pointing outside of the archive, we could relax this, but as it wouldn't be supported in wheels anyway, it seems unlikely.

Use tarfile filter on Python >= 3.12 when extracting sdist

---

flit/vendorized/readme/rst.py

Update to 44.0 from 2024-07-08:
https://github.com/pypa/readme_renderer/releases/tag/44.0
Apply the previous patch 1092d13 / #357.

Update vendorized readme_renderer
