- flit/__init__.py
- flit/common.py
Did that roughly in the bart. 
Was not remembering how to print Error message only cleanly.
> Better error message for missing docstring and version.

- flit/__init__.py
- flit/common.py
- flit/install.py
- flit/upload.py
- flit/wheel.py
Does not really belong in upload, or wheel, 
so might need to be splitted away. 
What do you think ?
> work on Register only flag.

- flit/inifile.py
OK, I know you don't want that, just that it works :-) 
Use pandoc to convert `Readme.md` to a rst description. [it works](https://pypi.python.org/pypi/SPQR) .
Feel free to close :-)
> Allow markdown description !

- flit/install.py
with a temporary requirements.txt build from metadata.requires_dist
closes #41
> `flit install` installs requirements

- flit/__main__.py
> Add a __main__.py to be able to invoke $ python -m flit

- doc/conf.py
Testing to see if it works on RTD.
> Put logo on top of sidebar.

- .travis.yml
- requirements-test.txt
This should work now that py.test 2.7.3 is out.
Ping @Carreau
> Start testing on Python 3.5

- flit/install.py
See line 164-175 have log.info, so for consistency...
> Log.info for script (same level as where module written)

- flit/inifile.py
- tests/test_inifile.py
Test will fail as `_validate_config`, actually pop values from config.
> Context Manager to modify config.

- flit.ini
- flit/common.py
- tests/test_common.py
PyPA `packaging` already normalize it, just need to check that normalization===identity.
> More extensive check os version number

- flit/__init__.py
- flit/installfrom.py
This adds a way to install directly from a source tarball or a Github repository.
> Add installfrom subcommand

- flit/inifile.py
Alternative to gh-69. I'm leaning towards this one, but not by much.
> Allow extra config sections with x- prefix

- README.rst
> Tiny typo.

- flit/inifile.py
- tests/samples/classifiers_with_space.ini
- tests/test_inifile.py
Closes 1/3 of #129 
Not doing all because 
1) it's late
2) I should work on other stuff
3) this just show the example for a potential extra contributor if @takluyver thinks allowing blank lines is ok.
> Allow blank lines in classifiers.

- flit/inifile.py
- tests/samples/dev_requires_with_empty_lines.ini
- tests/samples/requires_with_empty_lines.ini
- tests/test_inifile.py
This addresses https://github.com/takluyver/flit/issues/129.
> Ignore empty lines in all metadata list fields

- README.rst
pytoml is required dependency.
> Update readme on how to install the development version

- .travis.yml
Using some notes cribbed from https://github.com/travis-ci/travis-ci/issues/9069 to get Ubuntu 16.04 for that job.
> Test Python 3.7 on Travis

- flit/init.py
- tests/test_init.py
1. home-page is optional since https://github.com/takluyver/flit/issues/173 , so `flit init` shouldn't require that
2. `flit init` shouldn't accept a home-page value [for which `flit build` will refuse to build](https://github.com/takluyver/flit/blob/master/flit/validate.py#L210-L212)
> better validator for home-page field

- README.rst
> Add info about how published packages are installed

- doc/cmdline.rst
- flit/__init__.py
Close #294.
What should I supply to `.. versionadded::` in the documentation?
> Add environ FLIT_INSTALL_PYTHON

- doc/cmdline.rst
From discussion on #222
@jonathanchukinas: would this be clear from your perspective?
> Try to clarify how to control where packages are installed

- README.rst
- doc/cmdline.rst
- doc/index.rst
- doc/rationale.rst
> Add section about why you might want Flit, and what other options exist

- .gitignore
- doc/upload.rst
- flit/__init__.py
> change behaviour of --repository and update docs

- flit/build.py
- flit/upload.py
- flit/wheel.py
- pyproject.toml
- tests/samples/module1_toml/EG_README.rst
- tests/test_build.py
- tests/test_upload.py
- tests/test_wheel.py
These are both no longer really used (after a few simple changes to remove remaining uses of wheel_main), so I cleaned them up.
> Remove old wheel_main & verify functions

- flit/install.py
- tests/test_install.py
> Fix installing a package from the CWD

- flit_core/flit_core/common.py
- flit_core/flit_core/tests/samples/module2.py
> Fix inspecting version with a subscript assignment in the code

- doc/development.rst
- flit/vendorized/readme/rst.py
- tests/test_validate.py
Fixes #297. There was a simple config option for this right under my nose...
> Don't require Pygments for checking rst READMEs

- flit/install.py
Fixes #367, fixes conda/conda#9074
See this footnote: https://docs.python.org/3/library/csv.html#id3
> Fix newline for RECORD

- doc/development.rst
- doc/pyproject_toml.rst
- flit/init.py
- flit/tomlify.py
- flit_core/flit_core/build_thyself.py
- flit_core/flit_core/config.py
- flit_core/flit_core/sdist.py
- flit_core/flit_core/wheel.py
- pyproject.toml
- tests/test_init.py
- tests/test_tomlify.py
- tox.ini
Update of PR #315. Fixes #255.
> Replace 'pytoml' with 'toml'

- flit_core/flit_core/tests/samples/inclusion/LICENSES/README
- flit_core/flit_core/tests/test_wheel.py
- flit_core/flit_core/wheel.py
> Only add COPYING* & LICENSE* matches if they are regular files

- doc/pyproject_toml.rst
- flit/init.py
- flit/tomlify.py
- pyproject.toml
- tests/test_init.py
- tox.ini
This was in the last release, but I waited to document it so there was a chance for bugs to show up first.
> WIP: Document PEP 621 support

- .bumpversion.cfg
- pyproject.toml
This should make it a bit quicker for me to make new releases.
> Add config for bump2version

- flit/__init__.py
Log messages to say the default will change. This is the first step to disabling it by default.
Relates to #391
> Prepare for not generating setup.py by default

- flit/init.py
- tests/test_init.py
I noticed myself adding this to pyroject.toml after every new project init so I thought it would be a good addition.
> add license field to pyproject during init

- doc/cmdline.rst
> Fix docs to say that --no-setup-py is the default

- flit_core/pyproject.toml
Closes #482 
@takluyver @pradyunsg
> flit-core: add comment explaining where deps are listed

- doc/pyproject_toml.rst
Ref: https://github.com/pypa/flit/issues/513#issuecomment-1017407065
> docs: mention flit-core sdist behaviour

- .github/workflows/test.yml
Follows what was done to address https://github.com/pypa/setuptools/issues/3093
> Improve CI Resource Usage

- doc/history.rst
- flit_core/flit_core/config.py
- flit_core/flit_core/sdist.py
- flit_core/flit_core/tests/samples/inclusion/pyproject.toml
- flit_core/flit_core/tests/test_config.py
- flit_core/flit_core/tests/test_sdist.py
Signed-off-by: layday <layday@protonmail.com>
> Add support for recursive `**` includes and excludes

- flit/vcs/hg.py
> Included modified files in hg sdist

- flit_core/bootstrap_install.py
Part of https://github.com/pypa/flit/issues/570
> Support optional installation root

- doc/cmdline.rst
Closes https://github.com/pypa/flit/issues/276
> Document that token-based upload is supported

- doc/pyproject_toml.rst
- flit_core/flit_core/config.py
https://github.com/pypa/flit/issues/568
> Force bytecode directories and files always to exclude

- doc/history.rst
- doc/pyproject_toml.rst
> Add release notes for version 3.8

- flit_core/flit_core/wheel.py
- tests/test_wheel.py
> fix: regular flag was not set

- .readthedocs.yml
- doc/cmdline.rst
- doc/history.rst
@pypa/flit-team I was reminded by email that it's probably good to get another release out. I'll wait a day or two for comments, and push it out if there are none.
> Add release notes for 3.9

- doc/history.rst
I know it's minor, but may as well submit it since I noticed.
Scott K
> Fix typo in history.rst

- .github/workflows/test.yml
This should build packages for every PR, but push them only when I make a tag.
> Build & publish packages on Github actions

- flit_core/pyproject.toml
> Include tests in flit_core sdist

- .bumpversion.cfg
- doc/conf.py
- doc/history.rst
- flit/__init__.py
- flit_core/flit_core/__init__.py
- pyproject.toml
Release notes & version number
> Prepare to release 3.12
